import assert from 'node:assert/strict';
import fs from 'node:fs';
import React from 'react';
import * as jsxRuntime from 'react/jsx-runtime';
import TestRenderer, { act } from 'react-test-renderer';
import ts from 'typescript';
const saved = new Map();
global.window = { localStorage: { getItem: key => saved.get(key) || null, setItem: (key,value) => saved.set(key,value) } };
const module = { exports: {} };
const code = ts.transpileModule(fs.readFileSync(new URL('../src/ConfigurableLeadTable.tsx',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
new Function('require','module','exports',code)(id => id === 'lucide-react' ? {Eye:()=>null,Columns3:()=>null,Lock:()=>null} : id === 'react' ? React : id === 'react/jsx-runtime' ? jsxRuntime : { HorizontalScrollFrame: ({children}) => React.createElement('div',null,children) },module,module.exports);
const { ConfigurableLeadTable, normalizeColumnLayout } = module.exports;
const columns = [{key:'a',label:'Agent',width:100},{key:'b',label:'Homeowner',width:200},{key:'c',label:'Status',width:80,pinRight:true}];
const view = () => React.createElement(ConfigurableLeadTable,{columns,storageKey:'test-company'},React.createElement('tbody',null,React.createElement('tr',null,['A value','B value','C value'].map(text=>React.createElement('td',{key:text},text)))));
let renderer;
act(()=>{renderer=TestRenderer.create(view());});
assert.equal(renderer.root.findAllByType('td')[2].props.style.right,0);
assert.equal(renderer.root.findAllByType('th')[2].props.style.right,0);
const button = label => renderer.root.findAllByType('button').find(node=>node.children.filter(child=>typeof child==='string').join('')===label);
const checkbox = label => renderer.root.findAllByType('input').find(node=>node.props['aria-label']===label);
const values = () => renderer.root.findAllByType('td').map(node=>node.children.join(''));
act(()=>button('Lock / Unlock Columns').props.onClick());
act(()=>checkbox('Freeze Homeowner').props.onChange());
assert.equal(renderer.root.findAllByType('td')[1].props.style.left,100);
act(()=>button('Show / Hide Columns').props.onClick());
act(()=>checkbox('Show Agent').props.onChange());
assert.deepEqual(values(),['B value','C value']);
assert.equal(renderer.root.findAllByType('td')[0].props.style.left,0);
act(()=>button('Reorder Columns').props.onClick());
const moveStatus=renderer.root.findAllByType('button').find(node=>node.props['aria-label']==='Move Status left');
act(()=>moveStatus.props.onClick());
assert.deepEqual(values(),['C value','B value']);
assert.equal(renderer.root.findAllByType('td')[0].props.style.right,0);
act(()=>renderer.unmount());
act(()=>{renderer=TestRenderer.create(view());});
assert.deepEqual(values(),['C value','B value']);
assert.equal(renderer.root.findAllByType('td')[0].props.style.right,0);
assert.equal(renderer.root.findAllByType('th').length,2);
act(()=>button('Show / Hide Columns').props.onClick());
act(()=>button('Reset Columns').props.onClick());
assert.deepEqual(values(),['A value','B value','C value']);
assert.deepEqual(normalizeColumnLayout(columns,{order:['c','invalid','c'],hidden:['a','b','c'],frozen:['b','invalid']}),{order:['c','a','b'],hidden:['b','c'],frozen:['b']});
act(()=>renderer.unmount());
console.log('PASS hide, freeze offsets, aligned reordering, saved layout, and reset');

