import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon; create role authenticated;
create table company_representatives(id uuid,company_id uuid,access_token uuid,active boolean);
create table company_portal_settings(company_id uuid,company_access_token uuid,company_access_enabled boolean);
create table portal_leads(id uuid,company_id uuid,qc_status text,phone_number text,email text,form_data jsonb,updated_at timestamptz);
create table portal_appointments(id uuid,company_id uuid,lead_id uuid,representative_id uuid,company_visible_at timestamptz);
create function portal_resolve_company_access(uuid,uuid) returns uuid language plpgsql security definer set search_path='public' as $$ declare c uuid; begin select company_id into c from company_portal_settings where company_access_token=$2 and company_access_enabled; if c is null then raise exception 'Invalid link'; end if; return c; end $$;
insert into company_portal_settings values('${id(1)}','${id(2)}',true),('${id(3)}','${id(4)}',true);
insert into company_representatives values('${id(5)}','${id(1)}','${id(6)}',true),('${id(7)}','${id(1)}','${id(8)}',false);
insert into portal_leads values('${id(9)}','${id(1)}','approved','5551112222',null,'{}',now()),('${id(10)}','${id(1)}','pending','5551112222',null,'{}',now());
insert into portal_appointments values('${id(11)}','${id(1)}','${id(9)}','${id(5)}',now()),('${id(12)}','${id(1)}','${id(10)}','${id(5)}',null);`);
const sql=fs.readFileSync(new URL('../supabase/migrations/20261009123458_approved_portal_contact_editing.sql',import.meta.url),'utf8').split('-- Normalize future Lighting forms')[0];
await db.exec(sql);
const call=(appointment,token,rep=false,email='valid@example.test')=>db.query(`select portal_update_lead_contact('${id(appointment)}','${id(token)}',null,${rep},'5553334444','${email}')`);
await db.exec('set role anon');
await call(11,2);
await call(11,6,true);
await assert.rejects(()=>call(11,4));
await assert.rejects(()=>call(11,8,true));
await assert.rejects(()=>call(12,2));
await assert.rejects(()=>call(11,2,false,'invalid'));
await db.exec('reset role');
const row=(await db.query(`select phone_number,email,form_data from portal_leads where id='${id(9)}'`)).rows[0];
assert.equal(row.phone_number,'5553334444'); assert.equal(row.form_data.email,'valid@example.test');
console.log('PASS contact saving, assigned representative scope, company isolation, disabled links, unreleased leads and validation');
await db.close();
