import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Lock, Plus, RefreshCw, WalletCards } from 'lucide-react';
import { supabase } from './supabase';

type Obj = Record<string, any>;
function isoDate(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function money(v:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v||0)}
function currentSunday(){const d=new Date();d.setDate(d.getDate()-d.getDay());return isoDate(d)}

export function AdminPayroll(){
  const [periods,setPeriods]=useState<Obj[]>([]); const [entries,setEntries]=useState<Obj[]>([]); const [agents,setAgents]=useState<Obj[]>([]); const [teams,setTeams]=useState<Obj[]>([]); const [periodId,setPeriodId]=useState(''); const [week,setWeek]=useState(currentSunday); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  async function load(preferred?:string){setLoading(true);setError('');const [p,a,t]=await Promise.all([supabase.from('payroll_periods').select('*').order('week_start',{ascending:false}),supabase.from('agents').select('id,name,team_id,active').order('name'),supabase.from('teams').select('id,name,abbreviation')]);if(p.error||a.error||t.error)setError((p.error||a.error||t.error)?.message||'Unable to load payroll');const ps=(p.data||[]) as Obj[];setPeriods(ps);setAgents((a.data||[]) as Obj[]);setTeams((t.data||[]) as Obj[]);const chosen=preferred||periodId||ps[0]?.id||'';setPeriodId(chosen);if(chosen){const e=await supabase.from('payroll_entries').select('*').eq('payroll_period_id',chosen).order('created_at');if(e.error)setError(e.error.message);setEntries((e.data||[]) as Obj[])}else setEntries([]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(periodId)void loadEntries(periodId)},[periodId]);
  async function loadEntries(id:string){const e=await supabase.from('payroll_entries').select('*').eq('payroll_period_id',id);if(e.error)setError(e.error.message);else setEntries((e.data||[]) as Obj[])}
  async function generate(){setError('');const {data,error:e}=await supabase.rpc('generate_readyops_payroll_week',{p_date:week});if(e){setError(e.message);return;}await load(String(data||''))}
  const period=periods.find(p=>p.id===periodId);
  const stats=useMemo(()=>({agents:entries.length,qualified:entries.reduce((s,e)=>s+Number(e.qualified_leads||0),0),hours:entries.reduce((s,e)=>s+Number(e.hours||0),0),commission:entries.reduce((s,e)=>s+(Number(e.qualified_leads||0)*Number(e.lead_rate||0))+(Number(e.signed_contracts||0)*Number(e.signed_contract_rate||0)),0),bonuses:entries.reduce((s,e)=>s+Number(e.bonus||0),0),deductions:entries.reduce((s,e)=>s+Number(e.deductions||0),0),total:entries.reduce((s,e)=>s+Number(e.total_pay||0),0)}),[entries]);
  async function editEntry(row:Obj){if(period?.status==='locked'){setError('This payroll period is locked.');return;}const hours=promptNum('Hours',row.hours);if(hours===null)return;const base=promptNum('Base Pay',row.base_pay);if(base===null)return;const lead=promptNum('Lead Rate / Commission',row.lead_rate);if(lead===null)return;const signed=promptNum('Signed Contract Rate',row.signed_contract_rate);if(signed===null)return;const bonus=promptNum('Bonus',row.bonus);if(bonus===null)return;const deductions=promptNum('Deductions',row.deductions);if(deductions===null)return;const {error:e}=await supabase.from('payroll_entries').update({hours,base_pay:base,lead_rate:lead,signed_contract_rate:signed,bonus,deductions,updated_at:new Date().toISOString()}).eq('id',row.id);if(e)setError(e.message);else await loadEntries(periodId)}
  async function setStatus(status:string){if(!periodId)return;const patch:Obj={status,updated_at:new Date().toISOString()};if(status==='approved'){patch.approved_at=new Date().toISOString()}if(status==='paid'){patch.paid_at=new Date().toISOString()}if(status==='locked'){patch.locked_at=new Date().toISOString()}const {error:e}=await supabase.from('payroll_periods').update(patch).eq('id',periodId);if(e)setError(e.message);else await load(periodId)}
  return <div className="space-y-4">
    <div className="readyops-ref-page-header"><div className="readyops-ref-title-row"><h2>Payroll</h2><span>Sunday → Saturday</span></div><div className="readyops-ref-page-actions"><input type="date" value={week} onChange={e=>setWeek(e.target.value)} className="rounded-lg border p-2 text-xs"/><button className="readyops-ref-primary" onClick={()=>void generate()}><Plus size={14}/> Generate Week</button><button className="readyops-ref-secondary" onClick={()=>void load(periodId)}><RefreshCw size={14}/> Refresh</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="readyops-ref-card p-4"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-bold">Payroll Period<select value={periodId} onChange={e=>setPeriodId(e.target.value)} className="mt-1 min-w-64 rounded-lg border p-2"><option value="">No period selected</option>{periods.map(p=><option key={p.id} value={p.id}>{p.week_start} – {p.week_end} • {p.status}</option>)}</select></label>{period&&<><span className="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold uppercase text-blue-700">{period.status}</span><div className="ml-auto flex flex-wrap gap-2"><button className="readyops-ref-secondary" disabled={period.status==='locked'} onClick={()=>void setStatus('review')}>Review</button><button className="readyops-ref-secondary" disabled={period.status==='locked'} onClick={()=>void setStatus('approved')}><CheckCircle2 size={14}/> Approve</button><button className="readyops-ref-secondary" disabled={period.status==='locked'} onClick={()=>void setStatus('paid')}><WalletCards size={14}/> Mark Paid</button><button className="readyops-ref-primary" disabled={period.status==='locked'} onClick={()=>void setStatus('locked')}><Lock size={14}/> Lock Payroll</button></div></>}</div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><Kpi label="Agents" value={stats.agents}/><Kpi label="Qualified Leads" value={stats.qualified}/><Kpi label="Hours" value={stats.hours.toFixed(1)}/><Kpi label="Commission" value={money(stats.commission)}/><Kpi label="Bonuses" value={money(stats.bonuses)}/><Kpi label="Deductions" value={money(stats.deductions)}/><Kpi label="Total Payroll" value={money(stats.total)}/></section>
    <section className="readyops-ref-card overflow-hidden"><div className="readyops-ref-card-heading"><h3>Agent Payroll</h3><p className="mt-1 text-xs opacity-60">Generate a week first. Qualified and signed-contract counts come from ReadyOps leads; pay rates remain configurable per agent.</p></div>{loading?<div className="p-10 text-center opacity-60">Loading payroll…</div>:!periodId?<div className="p-10 text-center opacity-50">No payroll period yet. Pick a date and click Generate Week.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead><tr className="bg-slate-50 text-left text-[10px] uppercase opacity-60"><th className="p-3">Agent</th><th>Team</th><th>Hours</th><th>Qualified</th><th>Signed</th><th>Base</th><th>Lead Rate</th><th>Signed Rate</th><th>Bonus</th><th>Deduction</th><th>Total</th><th></th></tr></thead><tbody>{entries.map(r=>{const a=agents.find(x=>x.id===r.agent_id);const t=teams.find(x=>x.id===r.team_id);return <tr key={r.id} className="border-t"><td className="p-3 font-bold">{a?.name||'Unknown Agent'}</td><td>{t?.abbreviation||'—'}</td><td>{Number(r.hours||0).toFixed(1)}</td><td>{r.qualified_leads}</td><td>{r.signed_contracts}</td><td>{money(Number(r.base_pay))}</td><td>{money(Number(r.lead_rate))}</td><td>{money(Number(r.signed_contract_rate))}</td><td>{money(Number(r.bonus))}</td><td>{money(Number(r.deductions))}</td><td className="font-black">{money(Number(r.total_pay))}</td><td><button className="readyops-ref-secondary" disabled={period?.status==='locked'} onClick={()=>void editEntry(r)}>Edit Pay</button></td></tr>})}</tbody></table></div>}</section>
  </div>
}
function promptNum(label:string,value:any){const raw=window.prompt(label,String(value??0));if(raw===null)return null;const n=Number(raw);return Number.isFinite(n)?n:0}
function Kpi({label,value}:{label:string;value:string|number}){return <div className="readyops-ref-card p-4"><p className="text-[10px] font-extrabold uppercase opacity-60">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
