import { useEffect, useMemo, useState } from 'react';
import { Plus, RefreshCw, WalletCards } from 'lucide-react';
import { supabase } from './supabase';

type Obj = Record<string, any>;

function isoDate(d: Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function money(v:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v||0)}

export function AdminInvoices(){
  const [rows,setRows]=useState<Obj[]>([]); const [companies,setCompanies]=useState<Obj[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showCreate,setShowCreate]=useState(false);
  const now=new Date(); const first=new Date(now.getFullYear(),now.getMonth(),1);
  const [form,setForm]=useState<Obj>({company_id:'',period_start:isoDate(first),period_end:isoDate(now),billing_type:'per_lead',rate:'',additional:'0',discount:'0',due_date:isoDate(new Date(Date.now()+7*86400000))});
  async function load(){setLoading(true);setError('');const [i,c]=await Promise.all([supabase.from('invoices').select('*').order('created_at',{ascending:false}),supabase.from('roster_companies').select('id,name,state').order('name')]);if(i.error||c.error)setError((i.error||c.error)?.message||'Unable to load invoices');setRows((i.data||[]) as Obj[]);setCompanies((c.data||[]) as Obj[]);setLoading(false)}
  useEffect(()=>{void load()},[]);
  const stats=useMemo(()=>{const month=isoDate(first).slice(0,7);return {outstanding:rows.filter(r=>r.status!=='void').reduce((s,r)=>s+Number(r.balance||0),0),paid:rows.filter(r=>String(r.updated_at||'').startsWith(month)).reduce((s,r)=>s+Number(r.amount_paid||0),0),overdue:rows.filter(r=>r.status==='overdue').length,draft:rows.filter(r=>r.status==='draft').length,month:rows.filter(r=>String(r.created_at||'').startsWith(month)).length}},[rows]);
  async function createInvoice(){if(!form.company_id){setError('Select a company.');return;}setError('');const {error:e}=await supabase.rpc('create_readyops_invoice',{p_company_id:form.company_id,p_period_start:form.period_start,p_period_end:form.period_end,p_billing_type:form.billing_type,p_rate:Number(form.rate||0),p_additional_charges:Number(form.additional||0),p_discount:Number(form.discount||0),p_due_date:form.due_date||null});if(e){setError(e.message);return;}setShowCreate(false);await load()}
  async function updateStatus(id:string,status:string){const patch:Obj={status,updated_at:new Date().toISOString()};if(status==='paid'){const row=rows.find(r=>r.id===id);patch.amount_paid=Number(row?.total||0)}const {error:e}=await supabase.from('invoices').update(patch).eq('id',id);if(e)setError(e.message);else await load()}
  async function addPayment(row:Obj){const raw=window.prompt(`Payment amount for ${row.invoice_number}`,String(row.balance||0));if(!raw)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount<=0)return;const {error:e1}=await supabase.from('invoice_payments').insert({invoice_id:row.id,amount});if(e1){setError(e1.message);return;}const paid=Number(row.amount_paid||0)+amount;const status=paid>=Number(row.total||0)?'paid':'partial';const {error:e2}=await supabase.from('invoices').update({amount_paid:paid,status,updated_at:new Date().toISOString()}).eq('id',row.id);if(e2)setError(e2.message);else await load()}
  return <div className="space-y-4">
    <div className="readyops-ref-page-header"><div className="readyops-ref-title-row"><h2>Invoices</h2><span>Client Billing</span></div><div className="readyops-ref-page-actions"><button className="readyops-ref-secondary" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button><button className="readyops-ref-primary" onClick={()=>setShowCreate(true)}><Plus size={14}/> Create Invoice</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Outstanding Balance" value={money(stats.outstanding)}/><Kpi label="Paid This Month" value={money(stats.paid)}/><Kpi label="Overdue" value={stats.overdue}/><Kpi label="Draft Invoices" value={stats.draft}/><Kpi label="Invoices This Month" value={stats.month}/></section>
    <section className="readyops-ref-card overflow-hidden"><div className="readyops-ref-card-heading flex items-center gap-2"><WalletCards size={18}/><h3>Invoices</h3></div>{loading?<div className="p-10 text-center opacity-60">Loading invoices…</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="bg-slate-50 text-left text-[10px] uppercase opacity-60"><th className="p-3">Invoice</th><th>Company</th><th>Period</th><th>Leads</th><th>Total</th><th>Paid</th><th>Balance</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-bold text-blue-600">{r.invoice_number}</td><td>{companies.find(c=>c.id===r.company_id)?.name||'—'}</td><td>{r.period_start} → {r.period_end}</td><td>{r.billable_leads}</td><td>{money(Number(r.total))}</td><td>{money(Number(r.amount_paid))}</td><td className="font-bold">{money(Number(r.balance))}</td><td>{r.due_date||'—'}</td><td><select value={r.status} onChange={e=>void updateStatus(r.id,e.target.value)} className="rounded-lg border px-2 py-1 text-xs"><option value="draft">Draft</option><option value="sent">Sent</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="void">Void</option></select></td><td><button className="readyops-ref-secondary" disabled={r.status==='void'||r.status==='paid'} onClick={()=>void addPayment(r)}>Add Payment</button></td></tr>):<tr><td colSpan={10} className="p-10 text-center opacity-50">No invoices yet. Click Create Invoice to generate the first one from ReadyOps lead data.</td></tr>}</tbody></table></div>}</section>
    {showCreate&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"><div className="readyops-ref-card w-full max-w-2xl p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-lg font-bold">Create Invoice</h3><p className="text-xs opacity-60">Billable lead statuses default to Good and Signed Contract. Already billed Lead IDs are excluded.</p></div><button onClick={()=>setShowCreate(false)}>✕</button></div><div className="grid gap-3 md:grid-cols-2"><Field label="Company"><select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})} className="w-full rounded-lg border p-2"><option value="">Select company…</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Billing Type"><select value={form.billing_type} onChange={e=>setForm({...form,billing_type:e.target.value})} className="w-full rounded-lg border p-2"><option value="per_lead">Per Lead</option><option value="weekly_pay">Weekly Pay</option><option value="signed_contract">Signed Contract</option><option value="package_upfront">Package Upfront</option><option value="flat_fee">Flat Fee</option><option value="percentage">Percentage</option></select></Field><Field label="Period Start"><input type="date" value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})} className="w-full rounded-lg border p-2"/></Field><Field label="Period End"><input type="date" value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})} className="w-full rounded-lg border p-2"/></Field><Field label="Rate"><input type="number" step="0.01" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})} className="w-full rounded-lg border p-2" placeholder="0.00"/></Field><Field label="Due Date"><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className="w-full rounded-lg border p-2"/></Field><Field label="Additional Charges"><input type="number" step="0.01" value={form.additional} onChange={e=>setForm({...form,additional:e.target.value})} className="w-full rounded-lg border p-2"/></Field><Field label="Discount"><input type="number" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})} className="w-full rounded-lg border p-2"/></Field></div><div className="mt-5 flex justify-end gap-2"><button className="readyops-ref-secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="readyops-ref-primary" onClick={()=>void createInvoice()}>Create Draft Invoice</button></div></div></div>}
  </div>
}
function Kpi({label,value}:{label:string;value:string|number}){return <div className="readyops-ref-card p-4"><p className="text-[10px] font-extrabold uppercase opacity-60">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-bold">{label}<div className="mt-1">{children}</div></label>}
