import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ExternalLink, Loader2, RefreshCw, XCircle } from 'lucide-react';
import { supabase } from './supabase';
import { addDays, calendarWeekStart, formatDateLong, formatTime, localDate } from './portalUtils';
import { leadStatusClasses, leadStatusLabel } from './leadStatusPresentation';

type RangeMode='this'|'previous'|'all';
type LeadRow={lead_id:string;company_name:string;name:string;phone:string;address:string;appointment_date:string;start_time:string;qc_status:string;client_status?:string|null;appointment_status?:string|null;qc_reason?:string|null;inspector_notes?:string|null;payroll_week_start:string;payroll_week_end:string;pay_date:string};
type PortalCompany={id:string;public_slug:string;name:string;state?:string|null};
type AgentPortalData={agent:{name:string;portal_slug:string};appointments:LeadRow[];companies:PortalCompany[]};

export function AgentPortal({slug,token}:{slug:string;token:string}){
 const [data,setData]=useState<AgentPortalData|null>(null);const [mode,setMode]=useState<RangeMode>('this');const [payDate,setPayDate]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const range=useMemo(()=>{const monday=calendarWeekStart(); const sunday=addDays(monday,-1); if(mode==='previous'){return {start:localDate(addDays(sunday,-7)),end:localDate(addDays(sunday,-1))};} if(mode==='all')return {start:localDate(addDays(sunday,-90)),end:localDate(addDays(sunday,45))};return {start:localDate(sunday),end:localDate(addDays(sunday,6))};},[mode]);
 const load=useCallback(async()=>{setLoading(true);setError('');const {data:d,error:e}=await supabase.rpc('get_agent_portal',{p_access_token:token,p_start_date:range.start,p_end_date:range.end});const portalData=d as AgentPortalData|null;if(e){setError(e.message);setData(null)}else if(portalData?.agent?.portal_slug!==slug){setError('Agent link name does not match this access token.');setData(null)}else setData(portalData);setLoading(false)},[range.end,range.start,slug,token]);
 useEffect(()=>{void load()},[load]);
 const appointments=useMemo(()=>data?.appointments||[],[data?.appointments]); const payDates=useMemo(()=>[...new Set(appointments.map(a=>a.pay_date).filter(Boolean))].sort().reverse(),[appointments]);
 const visible=payDate?appointments.filter(a=>a.pay_date===payDate):appointments;
 const pending=visible.filter(a=>a.qc_status==='pending');const approved=visible.filter(a=>a.qc_status==='approved');const denied=visible.filter(a=>a.qc_status==='denied');
 if(loading&&!data)return <State title="Loading your appointments..." loading/>; if(!data)return <State title="Agent portal unavailable" detail={error||'This private link may be disabled.'}/>;
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-30 border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Ready Ops Agent Portal</p><h1 className="text-xl font-bold">{data.agent.name}</h1></div><button onClick={()=>void load()} className="rounded-lg border p-2"><RefreshCw size={16}/></button></div></header><main className="mx-auto max-w-6xl space-y-5 p-4">
  <section className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-end gap-2"><button onClick={()=>setMode('this')} className={btn(mode==='this')}>This Week</button><button onClick={()=>setMode('previous')} className={btn(mode==='previous')}>Previous Week</button><button onClick={()=>setMode('all')} className={btn(mode==='all')}>All Recent</button><label className="ml-auto text-xs font-bold text-slate-500">Payroll Pay Date<select value={payDate} onChange={e=>setPayDate(e.target.value)} className="ml-2 rounded-lg border px-3 py-2 text-sm text-slate-800"><option value="">All in date filter</option>{payDates.map(d=><option key={d} value={d}>{formatDateLong(d)}</option>)}</select></label></div><p className="mt-3 text-xs text-slate-500">Payroll week is Sunday–Saturday. A lead is assigned to payroll by its appointment date; the pay date is the following Saturday.</p></section>
  <section className="grid gap-3 sm:grid-cols-3"><Metric label="QC Pending" value={pending.length} tone="amber"/><Metric label="Approved" value={approved.length} tone="green"/><Metric label="QC Denied" value={denied.length} tone="red"/></section>
  <LeadSection title="QC Pending" description="Submitted to QC. The appointment slot is held, but the company cannot see it yet." rows={pending}/>
  <LeadSection title="Approved Leads" description="QC approved. The company can now see and work these appointments." rows={approved}/>
  <LeadSection title="QC Denied" description="These remain in your history with the QC denial reason." rows={denied}/>
  <section className="rounded-2xl border bg-white p-4"><h2 className="font-bold">Book Another Appointment</h2><p className="mt-1 text-sm text-slate-500">These links identify you automatically so new appointments are attached to this agent portal.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(data.companies||[]).map(c=><a key={c.id} href={`/book/${c.public_slug}?agent_token=${encodeURIComponent(token)}&agent=${encodeURIComponent(data.agent.name)}`} className="flex items-center justify-between rounded-xl border px-3 py-3 text-sm font-bold hover:border-blue-300 hover:bg-blue-50"><span>{c.name}{c.state?` — ${c.state}`:''}</span><ExternalLink size={14}/></a>)}</div></section>
 </main></div>
}
function LeadSection({title,description,rows}:{title:string;description:string;rows:LeadRow[]}){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-bold">{title} <span className="ml-1 text-sm text-slate-400">({rows.length})</span></h2><p className="text-xs text-slate-500">{description}</p></div>{rows.length===0?<div className="p-6 text-center text-sm text-slate-400">No appointments in this section.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="text-left text-[10px] uppercase text-slate-400"><th className="p-3">Company</th><th>Name</th><th>Phone</th><th>Address</th><th>Appointment</th><th>Status</th><th>Inspector Notes / QC Reason</th><th>Payroll</th></tr></thead><tbody>{rows.map(r=><tr key={r.lead_id} className="border-t"><td className="p-3 font-bold">{r.company_name}</td><td>{r.name}</td><td>{r.phone}</td><td className="max-w-[240px] truncate">{r.address}</td><td><div className="font-semibold">{formatDateLong(r.appointment_date)}</div><div className="text-xs text-blue-600">{formatTime(r.start_time)}</div></td><td><span className={`inline-flex rounded-md border px-2.5 py-1 text-[10px] font-black ${leadStatusClasses(r.qc_status==='approved'?(r.client_status||r.appointment_status||'pending'):r.qc_status)}`}>{leadStatusLabel(r.qc_status==='approved'?(r.client_status||r.appointment_status||'pending'):r.qc_status)}</span></td><td className="max-w-[260px] text-xs text-slate-600">{r.qc_status==='denied'?r.qc_reason||'QC denied':r.inspector_notes||'—'}</td><td className="text-xs"><div>{r.payroll_week_start} → {r.payroll_week_end}</div><div className="font-bold text-slate-700">Pay: {r.pay_date}</div></td></tr>)}</tbody></table></div>}</section>}
function Metric({label,value,tone}:{label:string;value:number;tone:string}){const c=tone==='green'?'border-emerald-200 bg-emerald-50 text-emerald-800':tone==='red'?'border-red-200 bg-red-50 text-red-800':'border-amber-200 bg-amber-50 text-amber-800';return <div className={`rounded-2xl border p-4 ${c}`}><p className="text-xs font-bold uppercase tracking-wide">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>}
function btn(active:boolean){return `rounded-lg px-3 py-2 text-xs font-bold ${active?'bg-blue-600 text-white':'border bg-white text-slate-600'}`}
function State({title,detail,loading}:{title:string;detail?:string;loading?:boolean}){return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><div className="text-center">{loading?<Loader2 className="mx-auto mb-3 animate-spin text-blue-600"/>:<XCircle className="mx-auto mb-3 text-red-500"/>}<h1 className="font-bold">{title}</h1>{detail&&<p className="mt-2 text-sm text-slate-500">{detail}</p>}<button onClick={()=>location.href='/'} className="mt-4 inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><ArrowLeft size={13}/> Back</button></div></div>}
