import { useState } from 'react';
import { PortalSection } from './PortalSection';
import { formatLeadAddress, formatTime, localDate } from './portalUtils';

type CalendarAppointment = { id: string; appointment_date: string; start_time: string; representative_id: string | null; location_label: string | null; lead: { full_name: string; address: string; city: string | null; state: string | null; zip_code: string | null; service_needed: string | null } };
export function CompanyCalendar<T extends CalendarAppointment>({ appointments, representatives, openLead, month, setMonth }: { appointments: T[]; representatives: { id: string; name: string }[]; openLead: (appointment: T) => void; month: Date; setMonth: (month: Date) => void }) {
  const [inspector, setInspector] = useState('');
  const [location, setLocation] = useState('');
  const rows = appointments.filter(a => (!inspector || a.representative_id === inspector) && (!location || a.location_label === location));
  const first = new Date(month.getFullYear(), month.getMonth(), 1 - month.getDay());
  const days = Array.from({ length: 42 }, (_, i) => new Date(first.getFullYear(), first.getMonth(), first.getDate() + i));
  return <section className="space-y-3"><h2 className="font-bold">Appointment Calendar</h2>
    <PortalSection title="Search & Filters"><div className="grid gap-2 sm:grid-cols-2"><label>Inspector<select className="mt-1 w-full rounded border p-2" value={inspector} onChange={e => setInspector(e.target.value)}><option value="">All inspectors</option>{representatives.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Location<select className="mt-1 w-full rounded border p-2" value={location} onChange={e => setLocation(e.target.value)}><option value="">All locations</option>{Array.from(new Set(appointments.map(a => a.location_label).filter(Boolean))).map(l => <option key={l} value={l!}>{l}</option>)}</select></label></div></PortalSection>
    <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">{month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h3><div className="flex gap-2"><button className="rounded border px-3 py-1" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>Previous Month</button><button className="rounded border px-3 py-1" onClick={() => setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1))}>Today</button><button className="rounded border px-3 py-1" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>Next Month</button></div></div>
    <div className="overflow-x-auto"><div className="grid min-w-[640px] grid-cols-7 overflow-hidden rounded-lg border bg-white">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => <div key={d} className="bg-blue-950 p-2 text-center font-bold text-white">{d}</div>)}{days.map(day => <div key={localDate(day)} className={`min-h-28 border-b border-r p-1.5 ${day.getMonth() !== month.getMonth() ? 'bg-slate-50 text-slate-500' : ''}`}><span className="font-bold">{day.getDate()}</span>{rows.filter(a => a.appointment_date === localDate(day)).sort((a, b) => a.start_time.localeCompare(b.start_time)).map(a => <button key={a.id} onClick={() => openLead(a)} className="mt-1 block w-full rounded border border-blue-100 bg-blue-50 p-1.5 text-left text-xs"><strong>{formatTime(a.start_time)} · {a.lead.full_name}</strong><span className="block">{formatLeadAddress(a.lead)}</span><span className="block">{a.lead.service_needed}</span></button>)}</div>)}</div></div>
  </section>;
}
